name: Run Playwright Tests

on:
  push:
    branches:
      - main  # or the branch you want to trigger the pipeline on
  pull_request:
    branches:
      - main  # or the branch you want to trigger the pipeline on

jobs:
  test:
    runs-on: ubuntu-latest  # You can also use windows-latest or macos-latest if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Specify the Node.js version you are using

    - name: Install dependencies
      run: npm install

    - name: Run Playwright tests
      run: npx playwright test
      env:
        # If you have environment variables, add them here
        # For example:
        # BASE_URL: ${{ secrets.BASE_URL }}
